stages:
  - build
  - publish_gitlab

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.internal.launcher.welcomeMessageEnabled=false"
  CI: "gitlab-ci"

cache:
  key: ${CI_PROJECT_NAME}
  paths:
    - .gradle

.build_release:
  image: docker.io/library/gradle:6.5.1-jdk8
  stage: publish_gitlab
  only:
    - master
    - tags
  artifacts:
    when: always
    paths:
      - build/distributions/*.zip
    expire_in: 360 days

.build_artifact:
  image: docker.io/library/gradle:6.5.1-jdk8
  stage: build
  only:
    refs:
      - merge_requests
  artifacts:
    when: always
    paths:
      - build/distributions/*.zip
    expire_in: 7 days

build_community:
  extends: .build_artifact
  script:
    - gradle -Dversion.prerelease=$CI_PIPELINE_ID-SNAPSHOT buildPlugin

build_ultimate:
  extends: .build_artifact
  script:
    - gradle -Dversion.prerelease=$CI_PIPELINE_ID-SNAPSHOT -PtypeIDE=IU buildPlugin

build_pycharm_professional:
  extends: .build_artifact
  script:
    - gradle -Dversion.prerelease=$CI_PIPELINE_ID-SNAPSHOT -PtypeIDE=PY buildPlugin

build_pycharm_community:
  extends: .build_artifact
  script:
    - gradle -Dversion.prerelease=$CI_PIPELINE_ID-SNAPSHOT -PtypeIDE=PC buildPlugin

release_community:
  extends: .build_release
  script:
    - gradle buildPlugin

release_ultimate:
  extends: .build_release
  script:
    - gradle -PtypeIDE=IU buildPlugin

release_pycharm_professional:
  extends: .build_release
  script:
    - gradle -PtypeIDE=PC buildPlugin

release_pycharm_community:
  extends: .build_release
  script:
    - gradle -PtypeIDE=PY buildPlugin