stages:
  - build

variables:
  GRADLE_OPTS: "-Dorg.gradle.internal.launcher.welcomeMessageEnabled=false"
  CI: "gitlab-ci"

cache:
  key: ${CI_PROJECT_NAME}
  paths:
    - .gradle

.build_release:
  image: registry.gitlab.com/pablomxnl/vale-cli-plugin/builder
  stage: build
  coverage: '/    - Instruction Coverage: ([0-9.]+)%/'
  only:
    - main
  artifacts:
    when: always
    paths:
      - build/distributions/*.zip
      - build/reports/tests
      - build/reports/jacoco/test
    reports:
      junit: build/test-results/test/**/TEST-*.xml
    expire_in: 360 days

.build_artifact:
  image: registry.gitlab.com/pablomxnl/vale-cli-plugin/builder
  stage: build
  coverage: '/    - Instruction Coverage: ([0-9.]+)%/'
  only:
    refs:
      - merge_requests
  artifacts:
    when: always
    paths:
      - build/distributions/*.zip
      - build/reports/tests
      - build/reports/jacoco/test
    reports:
      junit: build/test-results/test/**/TEST-*.xml
    expire_in: 7 days

build_artifact:
  extends: .build_artifact
  script:
    - gradle test
    - gradle -Dversion.prerelease=$CI_PIPELINE_ID-SNAPSHOT buildPlugin

release_artifact:
  extends: .build_release
  script:
    - gradle test
    - gradle buildPlugin
