= Vale CLI plugin
:icons: font

image:https://gitlab.com/pablomxnl/vale-cli-plugin/-/badges/release.svg[link="https://gitlab.com/pablomxnl/vale-cli-plugin/-/releases",title="Latest Release"]
image:https://img.shields.io/jetbrains/plugin/d/org.ideplugins.vale-cli-plugin[link="https://plugins.jetbrains.com/plugin/19613-vale-cli",title="Downloads"]
image:https://img.shields.io/gitlab/issues/open/pablomxnl/vale-cli-plugin?style=plastic[link="https://gitlab.com/pablomxnl/vale-cli-plugin/-/issues", title="GitLab issues"]
image:https://img.shields.io/jetbrains/plugin/r/stars/org.ideplugins.vale-cli-plugin[link="https://plugins.jetbrains.com/plugin/19613-vale-cli/reviews",title="Ratings"]
image:https://img.shields.io/jetbrains/plugin/v/org.ideplugins.vale-cli-plugin[link="https://plugins.jetbrains.com/plugin/19613-vale-cli",title="Version"]
image:https://gitlab.com/pablomxnl/vale-cli-plugin/badges/main/coverage.svg[link="https://pablomxnl.gitlab.io/vale-cli-plugin/coverage/html/index.html",title="Coverage report"]
image:https://img.shields.io/badge/Plugin-Documenation-blue[link="https://plugins.jetbrains.com/plugin/19613-vale-cli/docs",title="Plugin Documentation"]

Plugin for JetBrains IDE's that uses https://vale.sh[Vale CLI] to check markdown,asciidoc and other documentation formats

TIP: Pet project. Not associated with Errata (Vale CLI creators) or JetBrains whatsoever

== Documentation

See the plugin user documentation at the https://plugins.jetbrains.com/plugin/19613-vale-cli/docs[JetBrains Plugin Marketplace, window=_blank] or at the project https://pablomxnl.gitlab.io/vale-cli-plugin/index.html[Gitlab Pages, window=_blank]

== Build the plugin locally

[source]
----
./gradlew buildPlugin
----

== Run the plugin on an IntelliJ sandbox

[source]
----
./gradlew runForManualTests --no-configuration-cache
----
This https://gitlab.com/pablomxnl/vale-cli-plugin/-/blob/main/build.gradle.kts?ref_type=heads#L49-68[task] configures the IntelliJ sandbox to not confirm exit or show tips at startup among other things. It opens a sample project with a couple of markdown files to test with the plugin.

[source]
----
./gradlew runIde
----
The standard gradle intellij plugin task that runs the IDE with the developed plugin installed.

== Run tests inside container simulating a pipeline run
. Issue a docker run command mounting the project folder.
+
[source]
----
docker run --rm -u gradle -v "$PWD":/home/gradle/project -w /home/gradle/project registry.gitlab.com/pablomxnl/vale-cli-plugin/builder:0.0.28 gradle test
----
. Open the test results
+
[source]
----
open build/reports/tests/test/index.html
----
